"""Add user_id and timestamp to preferences

Revision ID: 030f0118cb1c
Revises: cf0adc12e03a
Create Date: 2025-05-20 17:04:15.537746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030f0118cb1c'
down_revision: Union[str, None] = 'cf0adc12e03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('preferences', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'preferences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preferences', type_='foreignkey')
    op.drop_column('preferences', 'timestamp')
    op.drop_column('preferences', 'user_id')
    # ### end Alembic commands ###
