"""Add preferences table

Revision ID: cf0adc12e03a
Revises: 989115366a37
Create Date: 2025-05-19 20:00:49.164462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0adc12e03a'
down_revision: Union[str, None] = '989115366a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kab_kota', sa.String(), nullable=True),
    sa.Column('budget_hotel', sa.String(), nullable=True),
    sa.Column('jenis_wisata', sa.String(), nullable=True),
    sa.Column('jenis_makan', sa.String(), nullable=True),
    sa.Column('prioritas', sa.String(), nullable=True),
    sa.Column('jumlah_paket', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_id'), 'preferences', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_super',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_super',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_preferences_id'), table_name='preferences')
    op.drop_table('preferences')
    # ### end Alembic commands ###
